[general]
live_config_reload = true

[window]
dimensions = { columns = 0, lines = 0 }
padding = { x = 10, y = 10 }
dynamic_padding = false
decorations = "Full"
opacity = 0.9
blur = true
title = "Alacritty"

[scrolling]
history=10000
multiplier=4

[font]
normal = { family = "Consolas", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size=12

[colors]
